### ISSUE TITLE
"require is not a function" when running a script note

### ISSUE THREAD

**Issue by riegera2412** [TriliumNext/Notes#433] opened 2024-09-16 08:16 UTC
### TriliumNext Version

v0.90.4/ also checked on latest

### What operating system are you using?

Other Linux

### What is your setup?

Server access only

### Operating System Version

Win1122H2

### Description

Hey there,

since I am not an experienced software guy, I might be wrong about claiming this to be a bug, so I apologize in advance.

I just came to realize, that the scripts I used in my zadam/trilium docker container are no longer working since I migrated to triliumnext/notes. When I run them manually I get the following error message:

```
JS Error: 500 POST script/run/WxG3UAQove1b - Load of script note "agenda_js_backend" (WxG3UAQove1b) failed with: require is not defined

Stack: Error
    at Object.w [as logError] (https://notes.my-domain.tld/assets/v0.90.4/app-dist/desktop.js:2:159531)
    at Object.g [as throwError] (https://notes.my-domain.tld/assets/v0.90.4/app-dist/desktop.js:2:149421)
    at c (https://notes.my-domain.tld/assets/v0.90.4/app-dist/desktop.js:2:145614)
    at async Object.error (https://notes.my-domain.tld/assets/v0.90.4/app-dist/desktop.js:2:144370)
```

The script note itself looks like this

```
/*
    Instructions: Paste the below into a new JS Backend Script note. Set the note variables to the IDs of the notes you want to use for your categories.
    Remember to set #run=hourly as a label for this note.
    To configure date formats use https://day.js.org/docs/en/display/format
*/

var isBetween = require('dayjs/plugin/isBetween')
api.dayjs.extend(isBetween)

async function run_script() {

    // User Set Variables
    let overdueNote = "8b3rzwL67j0f"
    let todayNote = "mv2ABG0eoPJt"
    let thisWeekNote = "INybeVMsh0N2"
    let thisMonthNote = "hmniEeFHVZv8"
    let thisYearNote = "6Na3iQc5jFzA"
    let futureNote = "ygDb4oauwS9v"
    let dueDateLabel = "dueDate"
    let dueTimeLabel = "dueTime"
    let useNumberOfDays = true     // If set to true, intervals are determined based on number of days

    // Dynamic Variables
    let now = api.dayjs()
    let startOfToday = now.startOf("day")
    let endOfToday = now.endOf("day")
    let endOfThisWeek = useNumberOfDays ? startOfToday.add(7, "day") : now.endOf("week")
    let endOfThisMonth = useNumberOfDays ? startOfToday.add(30, "day") : now.endOf("month")
    let endOfThisYear = useNumberOfDays ? startOfToday.add(365, "day") : now.endOf("year")


    for (let note of api.getNotesWithLabel(dueDateLabel)){
        // Get due date and time
        let dueDatePresent = note.getLabelValue(dueDateLabel) ? true : false
        let dueDate = api.dayjs(note.getLabelValue(dueDateLabel))
        let dueTime = note.hasLabel(dueTimeLabel) ? note.getLabelValue(dueTimeLabel) : ""
        let dueDateString = ""

        // Set Overdue Notes
        let isOverdue = (dueDatePresent && dueDate.isBefore(startOfToday))
        dueDateString = dueDate.format("MMM D, YYYY")
        api.toggleNoteInParent(false, note.noteId, overdueNote)
        api.toggleNoteInParent(isOverdue, note.noteId, overdueNote, dueDateString)

        // Set Today Notes
        let isToday = (dueDatePresent && dueDate.isBetween(startOfToday, endOfToday, null, '[)'))
        dueDateString = dueTime
        api.toggleNoteInParent(false, note.noteId, todayNote)
        api.toggleNoteInParent(isToday, note.noteId, todayNote, dueDateString)

        // Set This Week Notes
        let isThisWeek = (dueDatePresent && dueDate.isBetween(endOfToday, endOfThisWeek, null, '[)'))
        dueDateString = dueDate.format("ddd")
        api.toggleNoteInParent(false, note.noteId, thisWeekNote)
        api.toggleNoteInParent(isThisWeek, note.noteId, thisWeekNote, dueDateString)

        // Set This Month Notes
        let isThisMonth = (dueDatePresent && dueDate.isBetween(endOfThisWeek, endOfThisMonth, null, '[)'))
        dueDateString = dueDate.format("D")
        api.toggleNoteInParent(false, note.noteId, thisMonthNote)
        api.toggleNoteInParent(isThisMonth, note.noteId, thisMonthNote, dueDateString)

        // Set This Year Notes
        let isThisYear = (dueDatePresent && dueDate.isBetween(endOfThisMonth, endOfThisYear, null, '[]'))
        dueDateString = dueDate.format("MMM D")
        api.toggleNoteInParent(false, note.noteId, thisYearNote)
        api.toggleNoteInParent(isThisYear, note.noteId, thisYearNote, dueDateString)

        // Set Future Notes
        let isFuture = (dueDatePresent && dueDate.isAfter(endOfThisYear))
        dueDateString = dueDate.format("YYYY")
        api.toggleNoteInParent(false, note.noteId, futureNote)
        api.toggleNoteInParent(isFuture, note.noteId, futureNote, dueDateString)

    }
}
run_script()
```

It is the agenda function found on awesome trilium if I recall correctly and it worked perfectly before. "agenda_js_backend" is the name of the note containing the script and "WxG3UAQove1b" is the notes id.

Any help or insight on how to resolve this is very much appreciated.

**Comment by eliandoran** [comment] 2024-09-16 08:34
@riegera2412 , thank you for the report.
Could be a change since we did quite a bit of refactoring on the code.
I will test the script later this week and come back to you.

**Comment by riegera2412** [comment] 2024-09-24 05:48
Just to add what you probably have figured out yourself already.

After checking some of the other scripts I use and realize they work, I had a look at the agenda script again. The line of code that apparently causes the problem is

````
var isBetween = require('dayjs/plugin/isBetween')
````

which makes sense I guess since the function is literally named require. From what I read here it has something to do with a plugin. I am not aware I installed it manually, so I guess it is part of trilium. Dont know if this really helps.

André

**Comment by BeatLink** [comment] 2024-10-09 13:11
Any updates?

**Comment by eliandoran** [comment] 2024-10-12 08:06
@riegera2412 , OK, so I've finally had some time to look into this.

The issue is that the server used to run CJS (Common.js) modules which uses the `require` syntax. We switched to ESM on the server, so `require` does no longer exist. It is possible to use ESM-style imports which are slightly more difficult.

Instead of `require("dayjs/plugin/isBetween")` we can use `await import("dayjs/plugin/isBetween")`. Note that we have to use `await` in this case since ESM dynamic loading is async-only; this means you can't directly use `await` in the root of the script, you'd have to put it inside a `async` function.

In the case of the agenda script, it should be fixed via:

```javascript
/*
    Instructions: Paste the below into a new JS Backend Script note. Set the note variables to the IDs of the notes you want to use for your categories.
    Remember to set #run=hourly as a label for this note.
    To configure date formats use https://day.js.org/docs/en/display/format
*/

async function run_script() {
    await import("dayjs/plugin/isBetween");
    api.dayjs.extend(isBetween)

    // User Set Variables
    let overdueNote = "8b3rzwL67j0f"
    let todayNote = "Wc0GLYb0tymX"
    let thisWeekNote = "INybeVMsh0N2"
    let thisMonthNote = "hmniEeFHVZv8"
    let thisYearNote = "6Na3iQc5jFzA"
    let futureNote = "ygDb4oauwS9v"
    let dueDateLabel = "dueDate"
    let dueTimeLabel = "dueTime"
    let useNumberOfDays = true     // If set to true, intervals are determined based on number of days

    // Dynamic Variables
    let now = api.dayjs()
    let startOfToday = now.startOf("day")
    let endOfToday = now.endOf("day")
    let endOfThisWeek = useNumberOfDays ? startOfToday.add(7, "day") : now.endOf("week")
    let endOfThisMonth = useNumberOfDays ? startOfToday.add(30, "day") : now.endOf("month")
    let endOfThisYear = useNumberOfDays ? startOfToday.add(365, "day") : now.endOf("year")


    for (let note of api.getNotesWithLabel(dueDateLabel)){
        // Get due date and time
        let dueDatePresent = note.getLabelValue(dueDateLabel) ? true : false
        let dueDate = api.dayjs(note.getLabelValue(dueDateLabel))
        let dueTime = note.hasLabel(dueTimeLabel) ? note.getLabelValue(dueTimeLabel) : ""
        let dueDateString = ""

        // Set Overdue Notes
        let isOverdue = (dueDatePresent && dueDate.isBefore(startOfToday))
        dueDateString = dueDate.format("MMM D, YYYY")
        api.toggleNoteInParent(false, note.noteId, overdueNote)
        api.toggleNoteInParent(isOverdue, note.noteId, overdueNote, dueDateString)

        // Set Today Notes
        let isToday = (dueDatePresent && dueDate.isBetween(startOfToday, endOfToday, null, '[)'))
        dueDateString = dueTime
        api.toggleNoteInParent(false, note.noteId, todayNote)
        api.toggleNoteInParent(isToday, note.noteId, todayNote, dueDateString)

        // Set This Week Notes
        let isThisWeek = (dueDatePresent && dueDate.isBetween(endOfToday, endOfThisWeek, null, '[)'))
        dueDateString = dueDate.format("ddd")
        api.toggleNoteInParent(false, note.noteId, thisWeekNote)
        api.toggleNoteInParent(isThisWeek, note.noteId, thisWeekNote, dueDateString)

        // Set This Month Notes
        let isThisMonth = (dueDatePresent && dueDate.isBetween(endOfThisWeek, endOfThisMonth, null, '[)'))
        dueDateString = dueDate.format("D")
        api.toggleNoteInParent(false, note.noteId, thisMonthNote)
        api.toggleNoteInParent(isThisMonth, note.noteId, thisMonthNote, dueDateString)

        // Set This Year Notes
        let isThisYear = (dueDatePresent && dueDate.isBetween(endOfThisMonth, endOfThisYear, null, '[]'))
        dueDateString = dueDate.format("MMM D")
        api.toggleNoteInParent(false, note.noteId, thisYearNote)
        api.toggleNoteInParent(isThisYear, note.noteId, thisYearNote, dueDateString)

        // Set Future Notes
        let isFuture = (dueDatePresent && dueDate.isAfter(endOfThisYear))
        dueDateString = dueDate.format("YYYY")
        api.toggleNoteInParent(false, note.noteId, futureNote)
        api.toggleNoteInParent(isFuture, note.noteId, futureNote, dueDateString)

    }
}
run_script()
```

Let me know if it works out for you.

**Comment by eliandoran** [comment] 2024-10-12 08:15
Closing for now since the TriliumNext server does act accordingly, since we've switched from CJS to ESM. I will be sure to mention this in a migration guide document.

**Closed by eliandoran** 2024-10-12 08:15 UTC

**Comment by BeatLink** [comment] 2024-10-12 15:23
Thanks for the assist! works like a treat.

**Comment by BeatLink** [comment] 2024-10-13 16:40
@riegera2412 The Agenda plugin has been updated!

https://github.com/BeatLink/trilium-scripts

**Comment by riegera2412** [comment] 2024-10-16 07:25
@eliandoran thanks for solving this issue. I just tried it with "my" version of the agenda script and get the following error in the backend log.

```
07:18:51.647 Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/usr/src/app/node_modules/dayjs/plugin/isBetween' imported from /usr/src/app/src/services/script.js
Did you mean to import "dayjs/plugin/isBetween.js"?
```

Not sure, if I have to update the agenda backend script of @BeatLink to the recent version or if there is another issue maybe with my TriliumNext installation. I run it on docker with the compose file provided in the repo.

Sorry to bother you again with this. 
André
